version: "3.8"
services:
   bot-app:
     build: .
     container_name: app
     depends_on:
       - user-db
     ports:
      - target: 8080
        published: 8080
     environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/postgres
       - STRING_DATASOURCE_USERNAME=postgres
       - STRING_DATASOURCE_PASSWORD=root
   user-db:
     image: postgres
     container_name: user-db
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=root
