version: "3.8"
services:
   bot-app:
     build: .
     container_name: app
     depends_on:
       - users-db
     ports:
      - target: 8080
      - published: 8080
     environment:
       - SPRING_URL=jdbc:postgresql://users-db:5432/postgres
       - STRING_USER=postgres
       - STRING_PASSWORD=root
   users-db:
     image: postgres
     container_name: user-db
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=root
